import streamlit as st
import pandas as pd
import yaml
import plotly.graph_objects as go

from src.data.data_loader import load_and_validate_data
from src.models.training import prepare_training_data
from src.models.persistence import load_model
from src.backtest.engine import backtest_signals
from src.backtest.metrics import calculate_expectancy, calculate_sharpe_ratio
from src.backtest.comparison import calculate_strategy_vs_buy_and_hold

def load_config(path: str = "config/config.yaml") -> dict:
    with open(path, "r") as f:
        return yaml.safe_load(f)

@st.cache_resource
def get_model(path: str):
    return load_model(path)

@st.cache_data
def get_data(ticker: str, start: str, end: str):
    return load_and_validate_data(ticker=ticker, start=start, end=end)

@st.cache_data
def get_features(df: pd.DataFrame, threshold: float):
    return prepare_training_data(df, threshold=threshold)

# --- Main app ---

# Load configuration, model and market data
config = load_config()
model = get_model("outputs/model.pkl")
df = get_data(config["ticker"], config["data"]["start_date"], config["data"]["end_date"])

# Prepare features and generate predictions
dataset = get_features(df, config["model"]["threshold"])

X = dataset.drop(columns=["target"])

# Match the index of predictions with X
predictions = pd.Series(model.predict(X), index=X.index, name="prediction")

# Extract signals
buy_prediction = predictions[predictions == 1]
buy_signals = df.loc[buy_prediction.index, ["Close"]]

sell_prediction = predictions[predictions == -1]
sell_signals = df.loc[sell_prediction.index, ["Close"]]

# Dashboard header
st.title("BBCA.JK Trading Signal Dashboard")

st.subheader("Quantitative trading system")
st.markdown("This dashboard displays the trading signals generated by the trained machine learning model and evaluates their historical performance using the project's backtesting engine.")

# Key metrics
col1, col2, col3 = st.columns(3)
col1.metric(label="Trading Days", value=len(dataset))
col2.metric(label="Ticker", value=config["ticker"])
col3.metric(label="Threshold", value=config["model"]["threshold"])

# Select date range
with st.sidebar:
    st.header("Date Range")

    st.caption(
        f"Available data: {df.index.min().date()} "
        f"to {df.index.max().date()}"
    )

    start_date = st.date_input(
        "Start Date",
        value=df.index.min().date(),
        min_value=df.index.min().date(),
        max_value=df.index.max().date(),
    )

    end_date = st.date_input(
        "End Date",
        value=df.index.max().date(),
        min_value=df.index.min().date(),
        max_value=df.index.max().date(),
    )

if start_date > end_date:
    st.error("Start Date must be earlier than End Date.")
    st.stop()

# Filter price and trading signals according to date range
filtered_df = df[
    (df.index >= pd.Timestamp(start_date)) &
    (df.index <= pd.Timestamp(end_date))]


filtered_buy_signals = buy_signals[
    (buy_signals.index >= pd.Timestamp(start_date)) &
    (buy_signals.index <= pd.Timestamp(end_date))
]

filtered_sell_signals = sell_signals[
    (sell_signals.index >= pd.Timestamp(start_date)) &
    (sell_signals.index <= pd.Timestamp(end_date))
]

# Create price chart with signals
st.subheader("BBCA.JK Trading Signals")

fig = go.Figure()


# Close price
fig.add_trace(
    go.Scatter(
        x=filtered_df.index,
        y=filtered_df["Close"],
        mode="lines",
        name="Close Price"
    )
)


# BUY signals
fig.add_trace(
    go.Scatter(
        x=filtered_buy_signals.index,
        y=filtered_buy_signals["Close"],
        mode="markers",
        name="BUY",
        marker=dict(
            symbol="triangle-up",
            size=10,
            color="green"
        )
    )
)


# SELL signals
fig.add_trace(
    go.Scatter(
        x=filtered_sell_signals.index,
        y=filtered_sell_signals["Close"],
        mode="markers",
        name="SELL",
        marker=dict(
            symbol="triangle-down",
            size=10,
            color="red"
        )
    )
)


fig.update_layout(
    title="BBCA.JK Trading Signals Chart Visualization",
    xaxis_title="Date",
    yaxis_title="Price",
    hovermode="x unified",
    template="plotly_white",
    height=500
)


st.plotly_chart(
    fig,
    use_container_width=True
)

st.caption(
    "Green markers indicate BUY signals, while red markers "
    "indicate SELL signals."
)

st.subheader("Backtest Performance")

backtest_data = pd.DataFrame({"signal": predictions, "Close": df["Close"]})
backtest_data = backtest_data.dropna()
strategy_returns = backtest_signals(backtest_data, buy_fee=config["backtest"]["buy_fee"], sell_fee=config["backtest"]["sell_fee"])
strategy_returns = pd.Series(strategy_returns)

duration = (df.index.max() - df.index.min()).days / 365.25
total_trades = len(strategy_returns)
trades_per_year = total_trades / duration

# Calculate metrics
strategy_expectancy = calculate_expectancy(strategy_returns)
strategy_sharpe = calculate_sharpe_ratio(strategy_returns, trades_per_year=trades_per_year)

buy_hold_returns = pd.Series(df["Close"]).pct_change().dropna()
buy_hold_sharpe = calculate_sharpe_ratio(buy_hold_returns, trades_per_year=252)

performance_col1, performance_col2, performance_col3 = st.columns(3) 

performance_col1.metric(label="Total Trades", value=total_trades)
performance_col2.metric(label="Expectancy per Trade", value=f"{strategy_expectancy:.2%}")
performance_col3.metric(label="Sharpe Ratio", 
                         value=f"{strategy_sharpe:.2f}", 
                         delta=f"{strategy_sharpe - buy_hold_sharpe:+.2f} vs Buy & Hold")
st.caption("Delta Sharpe shows how much the strategy's performance differs from a buy-and-hold approach.")

st.subheader("Strategy vs Buy & Hold (with DCA) Investment")

# DCA 3 times a year
investment_dates = [
    pd.Timestamp("2022-01-10"),
    pd.Timestamp("2022-05-10"),
    pd.Timestamp("2022-10-10"),
    pd.Timestamp("2023-01-10"),
    pd.Timestamp("2023-05-10"),
    pd.Timestamp("2023-10-10"),
    pd.Timestamp("2024-01-10"),
    pd.Timestamp("2024-05-10"),
    pd.Timestamp("2024-10-10"),
    pd.Timestamp("2025-01-10"),
    pd.Timestamp("2025-05-10"),
    pd.Timestamp("2025-10-10"),
    pd.Timestamp("2026-01-10"),
    pd.Timestamp("2026-05-10")
]

initial_capital = config["backtest"]["initial_capital"]

comparison = calculate_strategy_vs_buy_and_hold(
    df=df,
    strategy_returns=strategy_returns,
    initial_capital=initial_capital,
    investment_dates=investment_dates,
)

strategy_final_value = comparison["strategy_final_value"]
strategy_profit = comparison["strategy_profit"]
strategy_return = comparison["strategy_return"]

periodic_final_value = comparison["periodic_final_value"]
periodic_profit = comparison["periodic_profit"]
periodic_return = comparison["periodic_return"]



# Display comparison
col1, col2 = st.columns(2)

col1.metric(
    "Strategy Final Value",
    f"${strategy_final_value:.2f}"
)

col2.metric(
    "Periodic Investment Final Value",
    f"${periodic_final_value:.2f}"
)

col1.metric(
    "Strategy Return",
    f"{strategy_return:.2%}"
)

col2.metric(
    "Periodic Investment Return",
    f"{periodic_return:.2%}"
)

col1.metric(
    "Strategy Profit",
    f"${strategy_profit:.2f}"
)

col2.metric(
    "Periodic Investment Profit",
    f"${periodic_profit:.2f}"
)

# Feature Importance
st.subheader("Feature Importance")

feature_importance = pd.Series(
    model.feature_importances_,
    index=X.columns
).sort_values()


fig = go.Figure()


fig.add_trace(
    go.Bar(
        x=feature_importance.values,
        y=feature_importance.index,
        orientation="h",
        name="Importance"
    )
)


fig.update_layout(
    title="Random Forest Feature Importance",
    xaxis_title="Importance",
    yaxis_title="Feature",
    template="plotly_white",
    height=400,
    showlegend=False
)


st.plotly_chart(
    fig,
    use_container_width=True
)


st.caption(
    "Longer bars indicate a feature's greater influence "
    "on the model's predictions.")


st.warning(
    "**Research Disclaimer:** This dashboard presents results from a historical "
    "backtest and is intended for research and educational purposes. Past performance "
    "does not guarantee future results. The strategy has not been validated in live "
    "market conditions and requires further testing before real-world deployment."
)